//Author: Phlus.com

Map<String, String> mapStrigns = {
  "following": "Following",
  "follow": "Follow",
  "unfollow": "Unfollow",
  "publish": "Publish",
  "vendor": "Vendor",
  "orders": "Orders",
  "reviews": "Reviews",
  "saveForLater": "Save for later",
  "clearCart": "Clear",
  "wishList": "Wishlist",
  "manageStore": "Manage store",
  "startSelling": "Start Selling",
  "pleaseFillCode": "Coupon field is empty.",
  "conversations": "Conversations",
  "messages": "Messages",
  "productCondition": "Product condition",
  "resetYourPassword": "Reset your password",
  "noPost": "This no longer exist!",
  "chat": "Chat",
  "relatedProducts": "Related Products",
  "crossSell": "CrossSell Products",
  "upSell": "UpSell Products",
  "addresses": "Addresses",
  "pleaseInput": "Please fill in all fields",
  "qty": "Qty",
  "save": "Save",
  "delete": "Delete",
  "currentPassword": "Current password",
  "newPassword": "New password",
  "confirmPassword": "Confirm password",
  "free": "Free",
  "store": "Store",
  "maxQuantity": "Max quanity reached",
  "review": "Review",
  "thankyou": "Thank you!",
  "add": "Add",
  "search": "Search",
  "recentlyViewd": "Recently viewed",
  "required": "Required",
  "emptyCartSubtitle": "Your cart is empty.",
  "wallet": "Wallet",
  "edit": "Edit",
  "soldIndividually": "Sold individually",
  "available": "Available",
  "stop": "Stop",
  "welcomeback": "Welcome back",
  "languageSuccess": "Updated successfully",
  "sales": "Sales",
  "balance": "Balance",
  "general": "General",
  "price": "Price",
  "variations": "Variations",
  "primary": "Primary",
  "camara": "Camara",
  "upload": "Upload",
  "images": "Images",
  "selected": "Selected",
  "salelabel": "Sale",
  "added": "Added",
  "reOrder": "Reorder",
  "yourOrderHasBeenAdded": "You order has been added",
  "expectedDeliveryDate": "Expected delivery date",
  "orderNo": "Order #",
  "writeReview": "Write a review",
  "def": "Default",
  "draft": "Draft",
  "brands": "Brands",
  "pleaseFillOutAllFields": "Please fill out all fields.",
  "choosePrice": "Choose price",
  "linkedProducts": "Linked products",
  "inventory": "Inventory",
  "coupons": "Coupons",
  "coupon": "Coupon",
  "reportProblem": "Report a problem",
  "card": "Card",
  "theme": "Theme",
  "views": "Views",
  "viewstore": "View Store",
  "goBack": "Go Back",
  "condition": "Condition",
  "discover": "Discover",
  "english": "English",
  "spanish": "Spanish",
  "french": "French",
  "chinese": "Chinese",
  "japanese": "Japanese",
  "seeAll": "See All",
  "buyNow": "Buy Now",
  "products": "Products",
  "addToCart": "Add To Cart ",
  "share": "Share",
  "cancel": "Cancel",
  "checkout": "Checkout",
  "startShopping": "Start Shopping",
  "shipping": "Shipping",
  "payment": "Payment",
  "firstName": "First Name",
  "lastName": "Last Name",
  "city": "City",
  "country": "Country",
  "phoneNumber": "Phone number",
  "email": "Email",
  "streetName": "Street Name",
  "shippingMethod": "Shipping Method",
  "address": "Address",
  "shippingAddress": "Shipping Address",
  "subtotal": "Subtotal",
  "total": "Total",
  "itsOrdered": "It's ordered!",
  "viewProduct": "View Product",
  "showAllMyOrdered": "Show All My Ordered",
  "backToShop": "Back to shop",
  "firstNameIsRequired": "The first name field is required",
  "lastNameIsRequired": "The last name field is required",
  "phoneIsRequired": "The phone number field is required",
  "emailIsRequired": "The email field is required",
  "passwordIsRequired": "The password field is required",
  "verifyPassword": "Verify password.",
  "paymentMethod": "Payment Method",
  "orderHistory": "Order History",
  "settings": "Settings",
  "language": "Languages",
  "rateTheApp": "Rate the app",
  "logout": "Logout",
  "login": "LogIn",
  "items": "items",
  "cart": "Cart",
  "shop": "Shop",
  "reset": "Reset",
  "dontHaveAccount": "Don't have an account?",
  "register": "Register",
  "close": "Close",
  "outOfStock": "Out of stock",
  "category": "Category",
  "clear": "Clear",
  "inStock": "In stock",
  "trackingNumberIs": "Tracking number is",
  "trackingPage": "Tracking page",
  "orderNotes": "Order notes",
  "loading": "Loading...",
  "totalTax": "Total tax",
  "discount": "Discount",
  "username": "Username",
  "password": "Password",
  "enterYourEmail": "Enter your email",
  "enterYourPassword": "Enter your password",
  "createAnAccount": "Create an account",
  "couponCode": "Coupon code",
  "refundRequest": "Request a refund",
  "remove": "Remove",
  "couponMsgSuccess": "Congratulations! Coupon code applied successfully",
  "writeYourNote": "Write your note",
  "orderSuccessTitle1": "You've successfully placed the order",
  "orderSuccessMsg1":
      "You can check status of your order by using our delivery status feature. You will receive an order confirmation e-mail with details of your order and a link to track its progress.",
  "orderSuccessTitle2": "Your account",
  "orderSuccessMsg2":
      "You can log to your account using e-mail and password defined earlier. On your account you can edit your profile data, check history of transactions, edit subscription to newsletter.",
  "signIn": "Sign In",
  "signinNotice": "Sign in for the best experience.",
  "done": "Done",
  "updateUserInfor": "Update Profile",
  "update": "Update",
  "agreeWithPrivacy": "Privacy and Term",
  "iAgree": "I agree with",
  "categories": "Categories",
  "stores": "Stores",
  "salePrice": "Sale price",
  "regularPrice": "Regular price",
  "imageGallery": "Image Gallery",
  "addingYourImage": "Adding your image",
  "productName": "Product name",
  "product": "Product",
  "addToCartSucessfully": "have been added to your cart",
  "pullToLoadMore": "Pull to Load more",
  "loadFail": "Load Failed!",
  "all": "All",
  "tags": "Tags",
  "attributes": "Attributes",
  "resetPassword": "Reset Password",
  "yourUsernameEmail": "Your username or email",
  "featured": "Featured",
  "onSale": "Sale",
  "no": "No",
  "yes": "Yes",
  "areYouSure": "Are you sure?",
  "orderStatusOnHold": "On-hold",
  "orderStatusPendingPayment": "Pending Payment",
  "orderStatusFailed": "Failed",
  "orderStatusProcessing": "Processing",
  "orderStatusPending": "Pending",
  "orderStatusCompleted": "Completed",
  "orderStatusCancelled": "Cancelled",
  "orderStatusRefunded": "Refunded",
  "goBackHomePage": "Go back to home page",
  "ok": "Ok",
  "notFound": "Not Found",
  "rateThisAppDescription":
      "If you like this app, please take a little bit of your time to review it. It really helps us and it shouldn't take you more than one minute.",
  "rate": "Rate",
  "noThanks": "No thanks",
  "maybeLater": "Maybe Later",
  "pleaseAgreeTerms": "Please agree with our terms",
  "noResultFound": "No Result Found",
  "loginCanceled": "The login is cancel",
  "tax": "Tax",
  "soldBy": "Sold by",
  "sku": "SKU",
  "pleaseSelectAllAttributes":
      "Please choose an option for each attribute of the product",
  "removeFromWishList": "Remove from WishList",
  "useNow": "Use Now",
  "expired": "Expired",
  "fixedCartDiscount": "Fixed Cart Discount",
  "fixedProductDiscount": "Fixed Product Discount",
  "refunds": "Refunds",
  "continues": "Continue",
  "orderId": "Order ID: ",
  "grossSales": "Gross Sales",
  "earnings": "Earnings",
  "allOrders": "Latest Sales",
  "yourEarningsThisMonth": "Your earnings this month",
  "searchOrderId": "Search with Order ID...",
  "yourOrders": "Your Orders",
  "editProductInfo": "Edit Product Info",
  "cantFindThisOrderId": "Can't find this order ID",
  "showDetails": "Show Details",
  "orLoginWith": "or login with",
  "notifications": "Notifications",
  "back": "Back",
  "deliveredTo": "Delivered to",
  "orderTotal": "Order Total",
  "addProduct": "Add Product",
  "takePicture": "Take Picture",
  "chooseFromGallery": "Choose From Gallery",
  "chooseFromServer": "Choose From Server",
  "selectImage": "Select Image",
  "more": "...more",
  "uploadProduct": "Upload Product",
  "name": "Name",
  "stockQuantity": "Stock Quantity",
  "manageStock": "Manage stock",
  "shortDescription": "Short Description",
  "updateInfo": "Update Info",
  "stock": "Stock",
  "pending": "Pending",
  "approve": "Approve",
  "approved": "Approved",
  "rating": "Rating",
  "change": "change",
  "reviewApproval": "Review Approval",
  "home": "Home",
  "updateStatus": "Update Status",
  "chatListScreen": "Messages",
  "cardNumber": "Card number",
  "expiredDate": "Expired Date",
  "expiredDateHint": "MM/YY",
  "cvv": "CVV",
  "cardHolder": "Card Holder",
  "mustSelectOneItem": "Must select 1 item",
  "optionsTotal": "Options total: {price}",
  "options": "Options",
  "pleaseSelectRequiredOptions": "Please select required options!",
  "location": "Location",
  "send": "Send",
  "typeYourMessage": "Type your message here...",
  "account": "Account",
  "brand": "Brand",
  "savedraft": "Save draft",
  "simple": "Simple",
  "variable": "Variable",
  "active": "Active",
  "gallery": "Gallery",
  "addAName": "Add a name",
  "addNew": "Add new",
  "selectAll": "Select all",
  "selectNone": "Select none",
  "visible": "Visible",
  "variation": "Variation",
  "direction": "Direction",
  "errorEmailFormat": "Please enter a valid email address.",
  "errorPhoneFormat": "Please enter a valid phone number.",
  "errorPasswordFormat": "Please enter a password of at least 8 characters",
  "enterYourEmailOrUsername": "Enter your email or username",
  "enterYourFirstName": "Enter your first name",
  "enterYourLastName": "Enter your last name",
  "enterYourPhoneNumber": "Enter your phone number",
  "refundOrderSuccess": "Request a refund for your order successfully!",
  "refundOrderFailed":
      "The request for a refund for the order was unsuccessful",
  "confirm": "Confirm",
  "confirmDeleteItem": "Are you sure you wish to delete this item?",
  "markAsRead": "Mark as read",
  "markAsUnread": "Mark as unread",
  "orderStatusShipped": "Shipped",
  "orderStatusReversed": "Reversed",
  "orderStatusCanceledReversal": "Canceled Reversal",
  "orderStatusChargeBack": "Charge Back",
  "orderStatusDenied": "Denied",
  "orderStatusExpired": "Expired",
  "orderStatusProcessed": "Processed",
  "orderStatusVoided": "Voided",
  "delivered": "Delivered",
  "fullName": "Full name",
  "updatePassword": "Update password",
  "customerDetail": "Customer detail",
  "storeInformation": "Store Information",
  "shipped": "Shipped",
  "privacyPolicy": "Privacy Policy",
  "title": "Title",
  "orderSummary": "Order Summary",
  "canNotLoadThisLink": "Can not load this link",
  "loadingLink": "Loading link...",
};
